version: '3.7'

services:
  app-server:
    build:
      context: polling-app-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: callicoder
      SPRING_DATASOURCE_PASSWORD: callicoder
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: polling-app-client
      dockerfile: Dockerfile
      target: build     # ðŸ‘ˆ this tells Docker to use the Node stage (before nginx)
    command: npm start  # ðŸ‘ˆ run React dev server instead of nginx
    working_dir: /app
    ports:
      - "9090:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_API_BASE_URL: http://localhost:8080/api
    volumes:
      - ./polling-app-client:/app
      - /app/node_modules
    depends_on:
      - app-server
    networks:
      - frontend

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: callicoder
      MYSQL_PASSWORD: callicoder
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:
